// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Banner: typeof import('./../src/components/Common/Banner.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./../src/components/Footer/index.vue')['default']
    Header: typeof import('./../src/components/Header/index.vue')['default']
    IconPark: typeof import('./../src/components/Common/IconPark.vue')['default']
    Pagination: typeof import('./../src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sec_index: typeof import('./../src/components/Pagination/sec_index.vue')['default']
    TypeNav: typeof import('./../src/components/TypeNav/index.vue')['default']
  }
}
